// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKXPDTNVLuWivDpD-Z4XYrbcACygYJ5PU',
    appId: '1:807547736259:web:271359f798f79d6cbdd276',
    messagingSenderId: '807547736259',
    projectId: 'uni-chat-69d59',
    authDomain: 'uni-chat-69d59.firebaseapp.com',
    storageBucket: 'uni-chat-69d59.firebasestorage.app',
    measurementId: 'G-PZBDH371NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_LdCcJVgeca4Ybw3LV6JMR1z_kWGaEs',
    appId: '1:807547736259:android:772a825a598066e5bdd276',
    messagingSenderId: '807547736259',
    projectId: 'uni-chat-69d59',
    storageBucket: 'uni-chat-69d59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQz0gwo9RUdJ_uN7r1GHY6hdqtfv9D1A',
    appId: '1:807547736259:ios:700ca06a72e70cebbdd276',
    messagingSenderId: '807547736259',
    projectId: 'uni-chat-69d59',
    storageBucket: 'uni-chat-69d59.firebasestorage.app',
    iosBundleId: 'com.example.uniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQz0gwo9RUdJ_uN7r1GHY6hdqtfv9D1A',
    appId: '1:807547736259:ios:700ca06a72e70cebbdd276',
    messagingSenderId: '807547736259',
    projectId: 'uni-chat-69d59',
    storageBucket: 'uni-chat-69d59.firebasestorage.app',
    iosBundleId: 'com.example.uniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKXPDTNVLuWivDpD-Z4XYrbcACygYJ5PU',
    appId: '1:807547736259:web:5eef8ff9375db5c5bdd276',
    messagingSenderId: '807547736259',
    projectId: 'uni-chat-69d59',
    authDomain: 'uni-chat-69d59.firebaseapp.com',
    storageBucket: 'uni-chat-69d59.firebasestorage.app',
    measurementId: 'G-Z420HYQ8XM',
  );
}
